name: Cypress Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run Docker image
        run: |
          docker build -t cypress-test .
          docker run -v ${PWD}/cypress/reports:/app/cypress/reports/mochawesome.html cypress-test

      - name: Save Cypress Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Cypress Artifacts
          path: cypress/reports/mochawesome.html
          retention-days: 7